# Generated by Django 5.2.7 on 2025-12-04 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Status')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anônima')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Transação')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign', verbose_name='Campanha')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-created_at'],
            },
        ),
    ]
