# Generated by Django 5.2.7 on 2025-12-04 14:10

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('total_donated', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Doado')),
                ('campaigns_created', models.IntegerField(default=0, verbose_name='Campanhas Criadas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
